# Generated by Django 4.2.6 on 2024-09-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_content', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL of the video', max_length=500, null=True),
        ),
    ]
