# Generated by Django 4.2.6 on 2024-09-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_content', '0004_post_likes_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='poster_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='poster_name',
        ),
    ]
